[package]
name = "scirust"
version = "0.1.0"
authors = ["Parker Henry <parkerh@sas.upenn.edu>", "Ian Longshore <lonian@seas.upenn.edu>"]

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
libc = "0.2.0"
num = "0.1.32"
